# Generated by Django 3.2.23 on 2024-01-25 18:44

import Campaign.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('dateActivated', models.DateTimeField(blank=True, null=True, verbose_name='Date activated')),
                ('dateCompleted', models.DateTimeField(blank=True, null=True, verbose_name='Date completed')),
                ('dateRetired', models.DateTimeField(blank=True, null=True, verbose_name='Date retired')),
                ('dateModified', models.DateTimeField(blank=True, null=True, verbose_name='Date modified')),
                ('activated', models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Activated?')),
                ('completed', models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Completed?')),
                ('retired', models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Retired?')),
                ('rawData', models.TextField(blank=True, editable=False, verbose_name='Raw data')),
                ('_str_name', models.TextField(blank=True, default='', editable=False)),
                ('campaignName', models.CharField(help_text='(max. 250 characters)', max_length=250, verbose_name='Campaign name')),
                ('campaignOptions', models.TextField(blank=True, null=True, verbose_name='Campaign task-specific options')),
                ('packageFile', models.FileField(blank=True, null=True, upload_to='Packages', validators=[Campaign.models._validate_package_file], verbose_name='Package file')),
            ],
            options={
                'ordering': ['_str_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrustedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Campaign.campaign', verbose_name='Campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('dateActivated', models.DateTimeField(blank=True, null=True, verbose_name='Date activated')),
                ('dateCompleted', models.DateTimeField(blank=True, null=True, verbose_name='Date completed')),
                ('dateRetired', models.DateTimeField(blank=True, null=True, verbose_name='Date retired')),
                ('dateModified', models.DateTimeField(blank=True, null=True, verbose_name='Date modified')),
                ('activated', models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Activated?')),
                ('completed', models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Completed?')),
                ('retired', models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Retired?')),
                ('rawData', models.TextField(blank=True, editable=False, verbose_name='Raw data')),
                ('_str_name', models.TextField(blank=True, default='', editable=False)),
                ('teamName', models.CharField(help_text='(max. 250 characters)', max_length=250, verbose_name='Team name')),
                ('requiredAnnotations', models.PositiveSmallIntegerField(help_text='(value in range=[1,32767])', verbose_name='Required annotations')),
                ('requiredHours', models.PositiveSmallIntegerField(help_text='(value in range=[1,32767])', verbose_name='Required hours')),
                ('activatedBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_campaignteam_activated_by', related_query_name='campaign_campaignteams', to=settings.AUTH_USER_MODEL, verbose_name='Activated by')),
                ('completedBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_campaignteam_completed_by', related_query_name='campaign_campaignteams', to=settings.AUTH_USER_MODEL, verbose_name='Completed by')),
                ('createdBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_campaignteam_created_by', related_query_name='campaign_campaignteams', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('members', models.ManyToManyField(related_name='campaign_campaignteam_members', related_query_name='campaign_campaignteams', to=settings.AUTH_USER_MODEL, verbose_name='Team members')),
                ('modifiedBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_campaignteam_modified_by', related_query_name='campaign_campaignteams', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('owner', models.ForeignKey(help_text='(must be staff member)', limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_campaignteam_owner', related_query_name='campaign_campaignteams', to=settings.AUTH_USER_MODEL, verbose_name='Team owner')),
                ('retiredBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_campaignteam_retired_by', related_query_name='campaign_campaignteams', to=settings.AUTH_USER_MODEL, verbose_name='Retired by')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['_str_name'],
            },
        ),
        migrations.CreateModel(
            name='CampaignData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('dateActivated', models.DateTimeField(blank=True, null=True, verbose_name='Date activated')),
                ('dateCompleted', models.DateTimeField(blank=True, null=True, verbose_name='Date completed')),
                ('dateRetired', models.DateTimeField(blank=True, null=True, verbose_name='Date retired')),
                ('dateModified', models.DateTimeField(blank=True, null=True, verbose_name='Date modified')),
                ('activated', models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Activated?')),
                ('completed', models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Completed?')),
                ('retired', models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Retired?')),
                ('rawData', models.TextField(blank=True, editable=False, verbose_name='Raw data')),
                ('_str_name', models.TextField(blank=True, default='', editable=False)),
                ('dataFile', models.FileField(upload_to='Batches', verbose_name='Data file')),
                ('dataValid', models.BooleanField(blank=True, default=False, editable=False, verbose_name='Data valid?')),
                ('dataReady', models.BooleanField(blank=True, default=False, editable=False, verbose_name='Data ready?')),
                ('activatedBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_campaigndata_activated_by', related_query_name='campaign_campaigndatas', to=settings.AUTH_USER_MODEL, verbose_name='Activated by')),
                ('completedBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_campaigndata_completed_by', related_query_name='campaign_campaigndatas', to=settings.AUTH_USER_MODEL, verbose_name='Completed by')),
                ('createdBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_campaigndata_created_by', related_query_name='campaign_campaigndatas', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['_str_name'],
            },
        ),
    ]
